server:
  port: 8081
  servlet:
    context-path: /

school:
  schoolName: 尚马
  schoolAddress: '高新区863软件园'
  testDate: 2018/03/03
  teachers: ['张三','李四','王五']

#  禁用thymeleaf缓存，提高开发效率
spring:
  thymeleaf:
    cache: false
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/zhu_admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false
  redis:
    password: root
#    host: 192.168.12.180:6380
    sentinel:
      master: mymaster
      nodes:
       - 192.168.12.180:26379
       - 192.168.12.180:26380
       - 192.168.12.180:26381

mybatis:
  mapper-locations: classpath:com/lhzh/*.xml
  type-aliases-package: com.lhzh
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl